databaseChangeLog:
  - changeSet:
      id: 5
      author: sayid
      preConditions:
        - not:
            tableExists:
              tableName: applications
      changes:
        - createTable:
            tableName: applications
            columns:
              - column:
                  name: id
                  type: serial
                  constraints:
                    primaryKey: true
              - column:
                  name: user_id
                  type: int
                  constraints:
                    foreignKeyName: fk_applications_user
                    references: Users(id)
                    onDelete: CASCADE
              - column:
                  name: group_id
                  type: int
                  constraints:
                    foreignKeyName: fk_applications_group
                    references: Groups(id)
                    onDelete: CASCADE
              - column:
                  name: send_at
                  type: timestamp
              - column:
                  name: status
                  type: varchar