spring:
  application:
    name: impl
  datasource:
    url: jdbc:postgresql://localhost:5432/tj-money
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml

aspect:
  enabled: false